### ISSUE TITLE
Misspelling in example code + a Question

### ISSUE THREAD

**Issue by bigMontana** [jamesa08/MIDIAnimatorDocs#1]
In the "Getting Started" section of the documentation you have the sample code to copy and paste into the Editor and run, the "3: Writing The Code" part that names the instrumentType as "evaluated" gets an error, it should be "evaluate".

That was a minor bug just to ask a question.  Is there currently any way to keep the animation going if the note gets held down?

Big fan of this add on, thanks

**Comment by jamesa08** [comment]
Thanks for reporting! Currently, that is on the list of to-do's and that should be added in the next major beta. If you can, let me know what you've been making! I'd love to see it.

Here's the list of to-do's by the way: https://github.com/users/jamesa08/projects/1/views/1
